window.esdocSearchIndex = [
  [
    "@iterable-iterator/range/src/backwardrange.js~backwardrange",
    "class/src/BackwardRange.js~BackwardRange.html",
    "<span>BackwardRange</span> <span class=\"search-result-import-path\">@iterable-iterator/range/src/BackwardRange.js</span>",
    "class"
  ],
  [
    "@iterable-iterator/range/src/forwardrange.js~forwardrange",
    "class/src/ForwardRange.js~ForwardRange.html",
    "<span>ForwardRange</span> <span class=\"search-result-import-path\">@iterable-iterator/range/src/ForwardRange.js</span>",
    "class"
  ],
  [
    "@iterable-iterator/range/src/range.js~range",
    "class/src/Range.js~Range.html",
    "<span>Range</span> <span class=\"search-result-import-path\">@iterable-iterator/range/src/Range.js</span>",
    "class"
  ],
  [
    "@iterable-iterator/range/src/backwardrangeiterator.js~backwardrangeiterator",
    "function/index.html#static-function-backwardRangeIterator",
    "<span>backwardRangeIterator</span> <span class=\"search-result-import-path\">@iterable-iterator/range/src/backwardRangeIterator.js</span>",
    "function"
  ],
  [
    "@iterable-iterator/range/src/forwardrangeiterator.js~forwardrangeiterator",
    "function/index.html#static-function-forwardRangeIterator",
    "<span>forwardRangeIterator</span> <span class=\"search-result-import-path\">@iterable-iterator/range/src/forwardRangeIterator.js</span>",
    "function"
  ],
  [
    "@iterable-iterator/range/src/range.js~range",
    "function/index.html#static-function-range",
    "<span>range</span> <span class=\"search-result-import-path\">@iterable-iterator/range/src/range.js</span>",
    "function"
  ],
  [
    "@iterable-iterator/range/src/rangeargs.js~rangeargs",
    "function/index.html#static-function-rangeArgs",
    "<span>rangeArgs</span> <span class=\"search-result-import-path\">@iterable-iterator/range/src/rangeArgs.js</span>",
    "function"
  ],
  [
    "@iterable-iterator/range/src/rangeiterator.js~rangeiterator",
    "function/index.html#static-function-rangeIterator",
    "<span>rangeIterator</span> <span class=\"search-result-import-path\">@iterable-iterator/range/src/rangeIterator.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/backwardrange.js",
    "file/src/BackwardRange.js.html",
    "src/BackwardRange.js",
    "file"
  ],
  [
    "src/backwardrange.js~backwardrange#[symbol.iterator]",
    "class/src/BackwardRange.js~BackwardRange.html#instance-method-[Symbol.iterator]",
    "src/BackwardRange.js~BackwardRange#[Symbol.iterator]",
    "method"
  ],
  [
    "src/backwardrange.js~backwardrange#constructor",
    "class/src/BackwardRange.js~BackwardRange.html#instance-constructor-constructor",
    "src/BackwardRange.js~BackwardRange#constructor",
    "method"
  ],
  [
    "src/backwardrange.js~backwardrange#has",
    "class/src/BackwardRange.js~BackwardRange.html#instance-method-has",
    "src/BackwardRange.js~BackwardRange#has",
    "method"
  ],
  [
    "src/forwardrange.js",
    "file/src/ForwardRange.js.html",
    "src/ForwardRange.js",
    "file"
  ],
  [
    "src/forwardrange.js~forwardrange#[symbol.iterator]",
    "class/src/ForwardRange.js~ForwardRange.html#instance-method-[Symbol.iterator]",
    "src/ForwardRange.js~ForwardRange#[Symbol.iterator]",
    "method"
  ],
  [
    "src/forwardrange.js~forwardrange#constructor",
    "class/src/ForwardRange.js~ForwardRange.html#instance-constructor-constructor",
    "src/ForwardRange.js~ForwardRange#constructor",
    "method"
  ],
  [
    "src/forwardrange.js~forwardrange#has",
    "class/src/ForwardRange.js~ForwardRange.html#instance-method-has",
    "src/ForwardRange.js~ForwardRange#has",
    "method"
  ],
  [
    "src/range.js",
    "file/src/Range.js.html",
    "src/Range.js",
    "file"
  ],
  [
    "src/range.js~range#constructor",
    "class/src/Range.js~Range.html#instance-constructor-constructor",
    "src/Range.js~Range#constructor",
    "method"
  ],
  [
    "src/range.js~range#get",
    "class/src/Range.js~Range.html#instance-method-get",
    "src/Range.js~Range#get",
    "method"
  ],
  [
    "src/range.js~range#length",
    "class/src/Range.js~Range.html#instance-member-length",
    "src/Range.js~Range#length",
    "member"
  ],
  [
    "src/range.js~range#start",
    "class/src/Range.js~Range.html#instance-member-start",
    "src/Range.js~Range#start",
    "member"
  ],
  [
    "src/range.js~range#step",
    "class/src/Range.js~Range.html#instance-member-step",
    "src/Range.js~Range#step",
    "member"
  ],
  [
    "src/range.js~range#stop",
    "class/src/Range.js~Range.html#instance-member-stop",
    "src/Range.js~Range#stop",
    "member"
  ],
  [
    "src/range.js~range#tostring",
    "class/src/Range.js~Range.html#instance-method-toString",
    "src/Range.js~Range#toString",
    "method"
  ],
  [
    "src/backwardrangeiterator.js",
    "file/src/backwardRangeIterator.js.html",
    "src/backwardRangeIterator.js",
    "file"
  ],
  [
    "src/forwardrangeiterator.js",
    "file/src/forwardRangeIterator.js.html",
    "src/forwardRangeIterator.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/range.js",
    "file/src/range.js.html",
    "src/range.js",
    "file"
  ],
  [
    "src/rangeargs.js",
    "file/src/rangeArgs.js.html",
    "src/rangeArgs.js",
    "file"
  ],
  [
    "src/rangeiterator.js",
    "file/src/rangeIterator.js.html",
    "src/rangeIterator.js",
    "file"
  ]
]